TOPDIR 	       ?= ../..

MAKE_TYPE       = bin
BUILD_PATH      = $(TOPDIR)/build/$(MAKE_OS)/apps/$(HereFolderName)


MODULES        += PI_BASE PI_GUI QT OPENGL QGLVIEWER

include $(TOPDIR)/scripts/make.conf


